### ISSUE TITLE
Can't unzip replay-source.pdb (0.2.2)

### ISSUE THREAD

**Issue by aqQnm0** [exeldro/obs-replay-source#1]
replay-source.pdb can't be unzipped in version 0.2.2, tried with Windows Explorer and Winrar. (Error: Unspecified Error 0x80004005, Windows 10 Pro 1809)
Worked fine in previous versions.
Maybe a new zip file would solve the problem.

![image](https://user-images.githubusercontent.com/11634943/50011771-33565d80-ffbd-11e8-86a4-f1297af6e1b1.png)

**Comment by exeldro** [comment]
Strange, I made a new zip and replaced the release version on github.
