### ISSUE TITLE
How do install on mac???

### ISSUE THREAD

**Issue by 3rror101** [exeldro/obs-replay-source#10]
The macOS folder has a .pkgproj file, what do I do with it (and the brew file)?????

**Comment by exeldro** [comment]
for installation on mac download the pkg from https://github.com/exeldro/obs-replay-source/actions/runs/80817687
right-click the .pkg file in Finder and select to "Open" the package installer, then click "Open" again to confirm.

**Comment by 3rror101** [comment]
It says no application to open this .pkgproj file

**Comment by exeldro** [comment]
The download url I gave should give you a pkg file, not a pkgproj file.
The pkgproj file is in the source files and is used to package the pkg file.

**Comment by exeldro** [comment]
Installing is the same way as my move transition plugin, so you can look at https://youtu.be/gLS8g5YqnIM to see how to install on Mac
