### ISSUE TITLE
No video Input from memory to ReplaySource - Linux

### ISSUE THREAD

**Issue by ogmkp** [exeldro/obs-replay-source#12]
Hi.

I've compiled the master branch and i'm testing on Linux Ubuntu 20.04 with OBS 25.0.8 and when i want to make a replay from the media source, it seems the plugin aren't filling the ReplaySource input.

info: [replay_source: 'ReplaySource'] Load replay pressed
info: [replay_source: 'ReplaySource'] replay added of 0.00 seconds
info: [replay_source: 'ReplaySource'] last hotkey switched to replay 1/1
info: User switched to scene 'Scène 6'

I've binded the F5 key to LoadReplay and F6 to Last and Switch to the ReplaySource scene.
When i press F6, it switch to the ReplaySource scene, no video, and if i set a NextScene, the plugin switch immediatly to the target scene without playing.

If i press the LoadReplay button in ReplaySource Properties, i see the only first frame in the Properties but no playing in composition, no playing too if i switch scenes.

Any help ?

Thanks.

**Comment by maxdrash** [comment]
I discovered now:
After starting OBS i have to change the source for a working replay input.
I need to select another source or scene for video source, it works, and doing a rollback to a Media Source it works too.
But only in the preview frame in ReplaySource Properties, no picture in OBS Program.

**Comment by maxdrash** [comment]
OK to get a full working ReplaySource:
Start OBS
Remove existing ReplaySource.
Add a new ReplaySource, choose a no wanted media source. Press OK to validate Properties.
Switch to another scene and get back to the ReplaySource Scene(or disable/enable the ReplaySource visibility).
Change the media source for the wanted media source.
Press LoadReplay binded with a Key then the key binded for Last and scene switching to ReplaySource.
All working.

**Comment by SiteBooster** [comment]
I seem to have the same issue: everytime I start my OBS, I first have to select another Video Source, and then my webcam device again before the replay works. If I don't do this, my replays won't work and I cannot load my replay scene anymore ([replay_source: 'Replay Source'] replay added of 0.00 seconds)

**Comment by ogmkp** [comment]
Closing this 2,5 year old issue.
