### ISSUE TITLE
[question] Lastest release github is not the same as the one on OBS Forum

### ISSUE THREAD

**Issue by umens** [exeldro/obs-replay-source#18]
Hi, the latest release here on github is v1.5.4 and on the OBS Forum it is v1.6.4. Is there a reason for that ?
I'm building something with  your plugin and for the build i need to download automatically the latest release at build time.
Can i trust the latest release on github to be the real latest or do i need to trust the latest on OBS Forum.
Thanks for the work anyway 👍

**Comment by exeldro** [comment]
The code on github is version 1.6.4. I stopped making releases on github to have only 1 place for the releases and the forum is the most accessible of the 2.
Every release on the forum is a [github action](https://github.com/exeldro/obs-replay-source/actions) artifact, so if you want to download it from github you can download the latest github action artifact from the master branch.

**Comment by umens** [comment]
Thank for the quick reply and explanations!
Closing the issue 😃
