### ISSUE TITLE
Previous Scene

### ISSUE THREAD

**Issue by kaiserdj** [exeldro/obs-replay-source#21]
I would like to know if there is any option that when the replay is finished, the next scene will be the scene before the change.

For example:
Scena (Lol) -> Press number 4 -> Change to scena Replay -> Finish replay and automatically return to Scena (Lol)

Scena (CSGO) -> Press number 4 -> Change to scene Replay -> End replay and automatically return to Scena (CSGO)

The only thing I have found, to be able to do this is a lua script, but I don't know if there is any option in this plugin

**Comment by OtterNas3** [comment]
You can use the same hotkey for "Load Replay" and for "Set Next Scene To Current"
This makes sure that after the Replay is finished it returns to the Scene where you started at
