### ISSUE TITLE
High Ram usage

### ISSUE THREAD

**Issue by OtterNas3** [exeldro/obs-replay-source#22]
Hey Exeldro,

is there any posibility to reduce the RAM usage?
Playing a 20s Replay at the moment is 20GB.
Maybe a option to use a different codec?
500mb for 1s of replay seems a bit too much.

Best regards,
Otter

**Comment by exeldro** [comment]
Because the plugin has the replay always instant ready and to not put any stress on the cpu, no encoding and decoding is done. To enable encoding would be a full rewrite of the plugin.

**Comment by OtterNas3** [comment]
Thanks for the info Exeldro!
So it is taking the RAW capture input.
Love the instant function of it, just thought there would maybe a way to lower the ram usage in a easier way.

Time to get more then 32gb Ram then again :)
