### ISSUE TITLE
In Studio Mode, RAM doubles

### ISSUE THREAD

**Issue by ruggi99** [exeldro/obs-replay-source#25]
Hi,
I noticed that when I go in Studio Mode, the RAM doubles. Is this a correct behavior?
Personally I use Studio Mode only if I have to edit another scene while I'm streaming / recording, so I don't want Replay Source to catch Preview input, but only Program input.
Is there an option to disable this behavior?

Thank you

**Comment by exeldro** [comment]
It can happen when in studio mode the source you are capturing for replay is duplicated. For sources like video capture devices that should not be a problem because they can not be duplicated. You can also disable the duplicate options for studio mode to prevent the double capturing of replay data.

**Comment by ruggi99** [comment]
Hi, thank you for the response.
In my case the RAM doubles even if there's the same scene on Preview and Program. This happens, for example, as soon as you go in Studio Mode. I tried with a Scene that has only a Source that is an external video capture device and the problem still exists.
In my situation, going into Studio Mode, with a Replay Source enabled, freezes OBS and I have to forcibly kill it. Instead disabling the Replay Source  makes OBS work normally. (also when Replay Source is enabled and Studio Mode disabled, OBS works normally)
I can't understand what you said in the last sentence. Where do I find that option? OBS settings?

Thank you

**Comment by exeldro** [comment]
You can find the duplicate options here:
![image](https://user-images.githubusercontent.com/5457024/108203514-e9301000-7122-11eb-8d7e-5edcd496bbc2.png)

**Comment by ruggi99** [comment]
Thank you.
Completely forgot about these options.
I have that option enabled because I want to assure myself that nothing wrong is being streamed and all works before making the transition.
With that option disabled, RAM doesn't double so it's okay.
I'm wondering why that source is duplicated, since is an external capture video device but I'll make some investigation for myself.
Sadly I can't use that option when I use replay Source.
Is there something you can do with this?
Can we put a warning in the docs for other users who might encounter this problem?

Thank you
