### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by pullhook** [exeldro/obs-replay-source#44]
Hi,

I read the other open issue called "MacOS Support" although the links to download those sources are expired. Also, the most recent version's download options for mac are ".zip", not ".pkg". The ".zip" creates a folder, not a ".pkg" file/folder. I cannot get the package installer utility to use the folder that is created from the ".zip" to install the plugin.

FWIW, I am using the a Macbook  pro with a M1 processor, just in case that is incompatible with the plugin.

Thanks in advance.

**Comment by exeldro** [comment]
Did you download from https://obsproject.com/forum/resources/replay-source.686/download ?
Did you try to install the arm or universal version of the plugin?

**Comment by pullhook** [comment]
I am not sure how I ended up downloading the source files rather than the .pkg version. It installed. Thanks for the reply.  Issue is resolved.
