### ISSUE TITLE
Trying to adjust the replay duration (in memory record) crashes Replay Filter

### ISSUE THREAD

**Issue by damnedOperator** [exeldro/obs-replay-source#45]
Hi, when trying to add the replay filter to my source in obs 29+, the filter immediately gets removed from the window on change of the replay duration. 
OBS 29.0.2 from official source. Replay Source Plugin 1.6.11

**Comment by exeldro** [comment]
You are not supposed to create replay filters yourself. The replay source should create the replay filter.

**Comment by damnedOperator** [comment]
Ok thanks. Can be closed then.

Exeldro ***@***.***> schrieb am Sa. 8. Apr. 2023 um 06:29:
