### ISSUE TITLE
Replay Filter Dissappears

### ISSUE THREAD

**Issue by chrisjameschamp** [exeldro/obs-replay-source#53]
The Replay Filter Disappears after a few seconds of applying it

https://github.com/exeldro/obs-replay-source/assets/38870317/dccd9b19-b3e3-4bfc-acdf-2ec5795e4b0f

 This is OBS 30.0.2

**Comment by exeldro** [comment]
@chrisjameschamp that is supposed to happen as the filter should only be created by the replay source.
